using Sttp.Data;

namespace Sttp.WireProtocol
{
    public enum CommandCode : byte
    {
        NegotiateSession = 0x00,
        MetadataRefresh = 0x01,
        Subscribe = 0x02,
        Unsubscribe = 0x03,
        SecureDataChannel = 0x04,
        RuntimeIDMapping = 0x05,
        DataPointPacket = 0x06,
        NoOp = 0xFF
    }

    public enum CommandCode2
    {
        /// <summary>
        /// Generated By User on startup.
        /// 
        /// Payload: 
        /// None
        /// 
        /// Handled by <see cref="MetadataSetSource.RequestAllTablesWithSchema"/>
        /// Respond With <see cref="AllTablesWithSchema"/>
        /// </summary>
        RequestAllTablesWithSchema,

        /// <summary>
        /// Generated By User on startup.
        /// 
        /// Payload: 
        /// string tableName;
        /// Guid cacheInstanceId
        /// long transactionID
        /// 
        /// Handled by <see cref="MetadataSetSource.RequestTableData"/>
        /// Respond With <see cref="TableDataPatch"/> or <see cref="TableDataComplete"/>
        /// </summary>
        RequestTableData,

        /// <summary>
        /// Response to <see cref="RequestAllTablesWithSchema"/>
        /// 
        /// Payload: Complex
        /// 
        /// Generated by <see cref="MetadataSetSource.RequestAllTablesWithSchema"/>
        /// Processed By <see cref="MetadataSetDestination.FillDataSet"/>
        /// </summary>
        AllTablesWithSchema,

        /// <summary>
        /// Generated by <see cref="MetadataSetSource.RequestTableData"/>
        /// Processed by <see cref="MetadataSetDestination.FillTable"/>
        /// </summary>
        TableDataPatch,

        /// <summary>
        /// Generated by <see cref="MetadataSetSource.RequestTableData"/>
        /// Processed by <see cref="MetadataSetDestination.FillTable"/>
        /// </summary>
        TableDataComplete,

    }

    public enum CommandCode3
    {
        /// <summary>
        /// Clears all metadata for a user.
        /// </summary>
        MetadataClear,

        /// <summary>
        /// Adds or replaces a table.
        /// </summary>
        MetadataAddTable,

        /// <summary>
        /// Deletes a table.
        /// </summary>
        MetadataDeleteTable,

        /// <summary>
        /// Updates the transaction version of the table.
        /// </summary>
        MetadataUpdateTable,
        
        /// <summary>
        /// Adds or replaces a column.
        /// </summary>
        MetadataAddColumn,

        /// <summary>
        /// Removes a column.
        /// </summary>
        MetadataDeleteColumn,

        /// <summary>
        /// Adds or updates a value.
        /// </summary>
        MetadataAddValue,

        /// <summary>
        /// Removes an entire row of data.
        /// </summary>
        MetadataDeleteRow,

    }
}